import { Game, TopPick, KProp, TotalPick, Parlay, ModelEdge, Confidence } from "./types";
import calibration from "./calibration.json";

export function americanToDecimal(odds: number): number {
  return odds > 0 ? 1 + odds / 100 : 1 + 100 / Math.abs(odds);
}

export function decimalToAmerican(decimal: number): number {
  return decimal >= 2 ? Math.round((decimal - 1) * 100) : Math.round(-100 / (decimal - 1));
}

export function formatOdds(odds: number): string {
  return odds > 0 ? `+${odds}` : `${odds}`;
}

export function calculateParlayPayout(odds: number[], bet: number = 10): { payout: number; profit: number; odds: number; bet: number } {
  const decimal = odds.reduce((acc, o) => acc * americanToDecimal(o), 1);
  const payout = Math.round(bet * decimal * 100) / 100;
  return {
    payout,
    profit: Math.round((payout - bet) * 100) / 100,
    odds: decimalToAmerican(decimal),
    bet,
  };
}

const HIGH_K_OFFENSES = new Set([
  "Rockies", "Mariners", "Athletics", "Angels", "White Sox",
  "Marlins", "Rays", "Diamondbacks", "Brewers",
]);

const LOW_K_OFFENSES = new Set([
  "Guardians", "Astros", "Cardinals", "Royals", "Padres",
  "Nationals", "Yankees", "Blue Jays",
]);

// Line-movement thresholds (American-odds cents). A moneyline that moved
// this many cents toward a team (e.g. -150 -> -180, or +180 -> +150) is
// interpreted as sharp money backing that team.
const SHARP_MOVE_CENTS = 20;
const MILD_MOVE_CENTS = 10;

// ---------------------------------------------------------------------------
// Model Edge: logistic win-probability model vs market implied probability
// ---------------------------------------------------------------------------

// League-average baselines used only to fill gaps when a team's stat is
// missing (rookie starters, TBD pitchers, no trends fetched). Centering on
// per-game *differences* between the two teams keeps the model relative, so
// these baselines only matter when one side lacks a stat.
const LEAGUE_AVG = {
  winRate: 0.5,
  runsPerGame: 4.5,
  starterEra: 4.25,
  k9: 8.6,
  bullpenEra: 4.1,
};

// A record must represent at least this many games before win rate counts as
// a real signal. A 2-0 start is noise; a 45-30 record is information. Teams
// below the floor fall back to the league baseline (and are marked
// incomplete), so early-season slates never produce confident fake edges.
const MIN_EDGE_GAMES = 4;

// Logistic coefficients. Each feature contributes to the log-odds z:
//   z = homeAdv + b1*(winRate diff) + b2*(R/G diff) + b3*(ERA diff)
//       + b4*(K/9 diff) + b5*(bullpen ERA diff)
// P(win) = sigmoid(z). The magnitudes are calibrated so a strong team vs a
// weak one (e.g. a -190 favorite) lands around a 70-75% model probability.
//
// Every feature is also capped (see MAX_FEATURE_LOGIT below) so a single
// extreme mismatch — say a 3.2 vs 5.6 starter ERA — can't dominate the model
// and print a +25% edge. Teams don't differ by 25 points of true win
// probability on one stat alone; caps keep extreme edges rare.
const HOME_ADV = 0.24;
const COEF_WIN_RATE = 2.8; // +0.10 win-rate diff ~ +7pp
const COEF_RUNS_PER_GAME = 0.22; // +1.0 R/G diff ~ +5.5pp
const COEF_STARTER_ERA = 0.28; // +1.0 ERA edge ~ +7pp
const COEF_K9 = 0.05; // +3.0 K/9 diff ~ +3.7pp
const COEF_BULLPEN_ERA = 0.18; // +1.0 bullpen ERA edge ~ +4.5pp

// Per-feature logit caps: the most one feature may move the win probability
// (a 0.5 logit cap ≈ +12pp; 0.4 ≈ +10pp; 0.3 ≈ +7.5pp). Applied symmetrically.
const MAX_FEATURE_LOGIT = {
  winRate: 0.6,
  runsPerGame: 0.4,
  starterEra: 0.5,
  k9: 0.3,
  bullpenEra: 0.4,
};

function clampFeature(term: number, cap: number): number {
  return Math.max(-cap, Math.min(cap, term));
}

// ---------------------------------------------------------------------------
// Platt scaling calibration
// ---------------------------------------------------------------------------

/**
 * Apply Platt scaling calibration to a raw logit.
 *
 * The backtest script fits parameters A and B so that:
 *   calibrated_prob = sigmoid(A * raw_logit + B)
 *
 * When A ≈ 1 and B ≈ 0, calibration is a no-op (the model is already
 * well-calibrated). Deviations from (1, 0) indicate the model needs
 * recalibration.
 *
 * Parameters are loaded from calibration.json which is generated by
 * running: npm run backtest
 */
function calibrateLogit(rawLogit: number): number {
  const { A, B } = calibration.plattScaling;
  return A * rawLogit + B;
}

// Edge thresholds for the A-D confidence grade. Data completeness (how many
// of the model's inputs actually exist for both teams) can knock a grade
// down a notch so we don't call an edge confident off a half-built model.
const EDGE_A = 8; // A: large edge + complete data
const EDGE_B = 5; // B: solid edge
const EDGE_C = 3; // C: marginal edge (still shown as a pick)

// Large edges (>10pp) are flagged as needing validation because they may
// indicate either a genuine opportunity or a model/data problem.
const HIGH_EDGE_THRESHOLD = 10;

export function sigmoid(z: number): number {
  return 1 / (1 + Math.exp(-z));
}

function parseWinRate(record: string): number | null {
  if (!record) return null;
  const [w, l] = record.split("-").map(Number);
  if (!Number.isFinite(w) || !Number.isFinite(l)) return null;
  const games = w + l;
  if (games < MIN_EDGE_GAMES) return null;
  return w / games;
}

interface TeamModelInputs {
  winRate: number;
  runsPerGame: number;
  starterEra: number;
  k9: number;
  bullpenEra: number;
  complete: boolean;
}

/** Gather the model inputs for one side of a game, filling gaps with league averages. */
function teamInputs(
  game: Game,
  side: "away" | "home",
): TeamModelInputs {
  const winRate = parseWinRate(side === "away" ? game.awayRecord : game.homeRecord);
  const runsPerGame = side === "away" ? game.awayRunsPerGame : game.homeRunsPerGame;
  const starterEra = side === "away" ? game.awayEra : game.homeEra;
  const k9 = side === "away" ? game.awayK9 : game.homeK9;
  const bullpenEra = side === "away" ? game.awayBullpenEra : game.homeBullpenEra;

  const present = [winRate, runsPerGame, starterEra, k9, bullpenEra]
    .filter((v): v is number => v != null).length;

  return {
    winRate: winRate ?? LEAGUE_AVG.winRate,
    runsPerGame: runsPerGame ?? LEAGUE_AVG.runsPerGame,
    starterEra: starterEra ?? LEAGUE_AVG.starterEra,
    k9: k9 ?? LEAGUE_AVG.k9,
    bullpenEra: bullpenEra ?? LEAGUE_AVG.bullpenEra,
    // Strong data = both teams have at least 4 of 5 core stats (counts both
    // sides, so >= 8 of 10 present).
    complete: present >= 4,
  };
}

// ---------------------------------------------------------------------------
// Core model functions
// ---------------------------------------------------------------------------

/**
 * Compute the raw log-odds (z-score) for one side of an MLB game.
 * This is the unscaled logistic input — NOT a probability.
 * Used internally by the model and exported for UI normalisation.
 */
export function computeRawLogit(
  t: TeamModelInputs,
  o: TeamModelInputs,
  isHome: boolean,
): number {
  let z = isHome ? HOME_ADV : 0;
  z += clampFeature((t.winRate - o.winRate) * COEF_WIN_RATE, MAX_FEATURE_LOGIT.winRate);
  z += clampFeature((t.runsPerGame - o.runsPerGame) * COEF_RUNS_PER_GAME, MAX_FEATURE_LOGIT.runsPerGame);
  z += clampFeature((o.starterEra - t.starterEra) * COEF_STARTER_ERA, MAX_FEATURE_LOGIT.starterEra);
  z += clampFeature((t.k9 - o.k9) * COEF_K9, MAX_FEATURE_LOGIT.k9);
  z += clampFeature((o.bullpenEra - t.bullpenEra) * COEF_BULLPEN_ERA, MAX_FEATURE_LOGIT.bullpenEra);
  return z;
}

/**
 * Compute normalised model probabilities (%) for both sides of a game.
 *
 * Raw logits are converted to odds-ratio space via sigmoid, then normalised
 * so that P(away) + P(home) = 100%. This is the mathematically correct way
 * to produce a two-outcome probability distribution — the old approach of
 * computing independent sigmoids allowed P(away) + P(home) > 100%.
 */
export function computeNormModelProbs(game: Game): {
  awayProb: number;
  homeProb: number;
  awayRawLogit: number;
  homeRawLogit: number;
  awayInputs: TeamModelInputs;
  homeInputs: TeamModelInputs;
} | null {
  const awayML = game.awayML;
  const homeML = game.homeML;
  if (!awayML || !homeML) return null;

  const t = teamInputs(game, "away");
  const o = teamInputs(game, "home");

  const awayRawLogit = computeRawLogit(t, o, false);
  const homeRawLogit = computeRawLogit(o, t, true);

  // Apply Platt scaling calibration to raw logits before normalisation.
  // This corrects systematic biases in the model's probability outputs.
  const eAway = sigmoid(calibrateLogit(awayRawLogit));
  const eHome = sigmoid(calibrateLogit(homeRawLogit));
  const total = eAway + eHome;

  // Clamp to [3%, 97%] to avoid displaying extreme probabilities
  const awayProb = Math.min(0.97, Math.max(0.03, eAway / total)) * 100;
  const homeProb = 100 - awayProb; // guaranteed to sum to exactly 100

  return { awayProb, homeProb, awayRawLogit, homeRawLogit, awayInputs: t, homeInputs: o };
}

/**
 * Logistic win probability (%) for one side of a game. Returns null when
 * there's no moneyline to anchor the matchup (no odds = no bettable game).
 *
 * NOTE: This uses the normalised (softmax) approach so both sides always
 * sum to exactly 100%.
 */
export function teamWinProbability(game: Game, side: "away" | "home"): number | null {
  const result = computeNormModelProbs(game);
  if (!result) return null;
  return side === "away" ? result.awayProb : result.homeProb;
}

/**
 * De-vigged (fair) market probability for one side.
 *
 * Raw implied probabilities from American odds include sportsbook vig and
 * typically sum to >100%. This function normalises them so both sides sum
 * to exactly 100%, giving the "fair" market price.
 *
 * Returns null if either side lacks odds.
 */
export function fairMarketProbability(
  awayML: number,
  homeML: number,
  side: "away" | "home",
): number | null {
  if (!awayML || !homeML) return null;

  // Raw implied probabilities (include vig)
  const awayImplied = (1 / americanToDecimal(awayML)) * 100;
  const homeImplied = (1 / americanToDecimal(homeML)) * 100;

  // De-vig: normalise so they sum to exactly 100%
  const total = awayImplied + homeImplied;
  if (total === 0) return null;

  return side === "away"
    ? (awayImplied / total) * 100
    : (homeImplied / total) * 100;
}

/**
 * Raw (vig-included) implied probability from a single moneyline.
 * Kept for backward compatibility and the totals/props analysis.
 */
export function marketProbability(ml: number): number {
  return (1 / americanToDecimal(ml)) * 100;
}

/**
 * Expected value as a percentage: (modelProb × decimalOdds) − 1.
 * Uses the model probability and actual sportsbook odds — NOT the
 * de-vigged market probability, because EV is about what YOU would
 * earn at the posted price.
 */
export function expectedValue(modelProbPct: number, americanOdds: number): number {
  const decimal = americanToDecimal(americanOdds);
  return (modelProbPct / 100) * decimal - 1; // as a fraction; multiply by 100 for %
}

/** A-D confidence grade shared by all sports' model-edge layers. */
export function edgeConfidence(edge: number, complete: boolean): Confidence {
  if (edge >= EDGE_A) return complete ? "A" : "B";
  if (edge >= EDGE_B) return complete ? "B" : "C";
  if (edge >= EDGE_C) return "C";
  return "D";
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

/**
 * Validate that model probabilities and fair-market probabilities sum to ~100%
 * for a two-team moneyline game. Logs an error if validation fails.
 * Returns true if valid.
 */
function validateGameProbabilities(
  game: Game,
  modelAway: number,
  modelHome: number,
  fairMktAway: number,
  fairMktHome: number,
): boolean {
  const EPSILON = 0.5; // allow rounding tolerance
  let valid = true;

  const modelSum = modelAway + modelHome;
  if (Math.abs(modelSum - 100) > EPSILON) {
    console.error(
      `[EDGE-VALIDATION] ${game.awayTeam} @ ${game.homeTeam}: ` +
      `model probabilities sum to ${modelSum.toFixed(2)}% (expected ~100%). ` +
      `away=${modelAway.toFixed(2)}% home=${modelHome.toFixed(2)}%`
    );
    valid = false;
  }

  const fairSum = fairMktAway + fairMktHome;
  if (Math.abs(fairSum - 100) > EPSILON) {
    console.error(
      `[EDGE-VALIDATION] ${game.awayTeam} @ ${game.homeTeam}: ` +
      `fair market probabilities sum to ${fairSum.toFixed(2)}% (expected ~100%). ` +
      `away=${fairMktAway.toFixed(2)}% home=${fairMktHome.toFixed(2)}%`
    );
    valid = false;
  }

  // Validate odds are numeric and non-zero
  if (!game.awayML || !game.homeML || !Number.isFinite(game.awayML) || !Number.isFinite(game.homeML)) {
    console.error(
      `[EDGE-VALIDATION] ${game.awayTeam} @ ${game.homeTeam}: ` +
      `invalid odds — awayML=${game.awayML} homeML=${game.homeML}`
    );
    valid = false;
  }

  // Validate probabilities are in range
  for (const [label, val] of [["modelAway", modelAway], ["modelHome", modelHome], ["fairAway", fairMktAway], ["fairHome", fairMktHome]] as [string, number][]) {
    if (!Number.isFinite(val) || val < 0 || val > 100) {
      console.error(
        `[EDGE-VALIDATION] ${game.awayTeam} @ ${game.homeTeam}: ` +
        `${label}=${val} is out of range [0, 100]`
      );
      valid = false;
    }
  }

  return valid;
}

// ---------------------------------------------------------------------------
// Compute model edges
// ---------------------------------------------------------------------------

/**
 * Compute the model edge for every team in every game with odds and surface
 * the positive ones (model likes the team more than the market does).
 *
 * Key improvements over the previous version:
 * 1. Model probabilities are NORMALISED via softmax (both sides sum to 100%).
 * 2. Market probabilities are DE-VIGGED (both sides sum to 100%).
 * 3. Edge = normalised model − de-vigged market (not raw implied).
 * 4. EV is computed using actual sportsbook odds and model probability.
 * 5. TBD pitchers are flagged with pitcherConfirmed = false.
 * 6. High edges (>10pp) are flagged for validation.
 * 7. Validation assertions are run on every game.
 */
export function computeModelEdges(games: Game[]): ModelEdge[] {
  const edges: ModelEdge[] = [];

  for (const game of games) {
    const probs = computeNormModelProbs(game);
    if (!probs) continue;

    // No meaningful model data on either side (e.g. 0-0 records, no trends)
    // means every "edge" would just be 50% vs the market price — noise, not
    // signal. Skip these games entirely.
    if (!probs.awayInputs.complete && !probs.homeInputs.complete) continue;

    // De-vig the market
    const fairAway = fairMarketProbability(game.awayML, game.homeML, "away");
    const fairHome = fairMarketProbability(game.awayML, game.homeML, "home");
    if (fairAway == null || fairHome == null) continue;

    // Validate that probabilities sum correctly
    validateGameProbabilities(game, probs.awayProb, probs.homeProb, fairAway, fairHome);

    // Both pitchers confirmed?
    const pitcherConfirmed = !!game.awayPitcher && !!game.homePitcher &&
      game.awayPitcher !== "TBD" && game.homePitcher !== "TBD";

    for (const side of ["away", "home"] as const) {
      const team = side === "away" ? game.awayTeam : game.homeTeam;
      const abbrev = side === "away" ? game.awayAbbrev : game.homeAbbrev;
      const opponent = side === "away" ? game.homeTeam : game.awayTeam;
      const ml = side === "away" ? game.awayML : game.homeML;
      if (!ml) continue;

      const modelProb = side === "away" ? probs.awayProb : probs.homeProb;
      const fairMktProb = side === "away" ? fairAway : fairHome;
      const edge = modelProb - fairMktProb;
      const ev = expectedValue(modelProb, ml) * 100; // as percentage

      const tInputs = side === "away" ? probs.awayInputs : probs.homeInputs;
      const oInputs = side === "away" ? probs.homeInputs : probs.awayInputs;

      const reasons: string[] = [];
      if (tInputs.winRate > oInputs.winRate + 0.03) reasons.push(`${(tInputs.winRate * 100).toFixed(0)}% win rate`);
      if (tInputs.runsPerGame > oInputs.runsPerGame + 0.3) reasons.push(`${tInputs.runsPerGame.toFixed(2)} R/G offense`);
      if (tInputs.starterEra < oInputs.starterEra - 0.3) reasons.push(`Starter ERA ${tInputs.starterEra.toFixed(2)}`);
      if (tInputs.k9 > oInputs.k9 + 1) reasons.push(`K/9 ${tInputs.k9.toFixed(1)}`);
      if (tInputs.bullpenEra < oInputs.bullpenEra - 0.3) reasons.push(`BP ERA ${tInputs.bullpenEra.toFixed(2)}`);
      if (side === "home") reasons.push("Home field");
      if (!pitcherConfirmed) reasons.push("⚠ TBD pitcher(s)");

      edges.push({
        team,
        abbrev,
        opponent,
        gameId: game.id,
        ml,
        home: side === "home",
        modelProb: Math.round(modelProb * 10) / 10,
        fairMarketProb: Math.round(fairMktProb * 10) / 10,
        edge: Math.round(edge * 10) / 10,
        ev: Math.round(ev * 10) / 10,
        confidence: edgeConfidence(edge, tInputs.complete && oInputs.complete),
        reasons,
        pitcherConfirmed,
      });
    }
  }

  return edges
    .filter(e => e.edge >= EDGE_C)
    .sort((a, b) => b.edge - a.edge)
    .slice(0, 6);
}

// ---------------------------------------------------------------------------
// Top Favorite Picks — ranked by model edge + EV (not just odds magnitude)
// ---------------------------------------------------------------------------

export function analyzeFavorites(games: Game[]): TopPick[] {
  const picks: (TopPick & { score: number })[] = [];

  for (const game of games) {
    const probs = computeNormModelProbs(game);
    if (!probs) continue;

    const fairAway = fairMarketProbability(game.awayML, game.homeML, "away");
    const fairHome = fairMarketProbability(game.awayML, game.homeML, "home");
    if (fairAway == null || fairHome == null) continue;

    const pitcherConfirmed = !!game.awayPitcher && !!game.homePitcher &&
      game.awayPitcher !== "TBD" && game.homePitcher !== "TBD";

    // Evaluate both sides — an underdog with positive EV is a better bet
    // than a heavy favorite with negative EV.
    const sides = [
      { side: "away" as const, team: game.awayTeam, opponent: game.homeTeam, ml: game.awayML, modelProb: probs.awayProb, fairMkt: fairAway },
      { side: "home" as const, team: game.homeTeam, opponent: game.awayTeam, ml: game.homeML, modelProb: probs.homeProb, fairMkt: fairHome },
    ];

    for (const s of sides) {
      if (!s.ml) continue;

      const edge = s.modelProb - s.fairMkt;
      const ev = expectedValue(s.modelProb, s.ml) * 100; // as percentage

      // Only include picks with positive edge (model disagrees with market)
      if (edge <= 0) continue;

      // Line movement signal
      const isHome = s.side === "home";
      const favOpen = isHome ? game.homeMLOpen : game.awayMLOpen;
      const lineMoveBonus = (() => {
        if (!favOpen) return 0;
        const move = s.ml - favOpen;
        if (move <= -SHARP_MOVE_CENTS) return 3; // sharp money on this side
        if (move <= -MILD_MOVE_CENTS) return 1;
        return 0;
      })();

      // Score: edge is the primary factor, EV confirms it, pitcher certainty
      // adds confidence. Odds magnitude alone does NOT drive the score.
      const score =
        edge * 0.5 +           // model edge (pp)
        Math.max(0, ev) * 0.3 + // positive EV bonus
        (probs.awayInputs.complete && probs.homeInputs.complete ? 1.5 : 0) + // data quality
        (pitcherConfirmed ? 1.0 : 0) + // pitcher certainty
        lineMoveBonus; // sharp money signal

      const reasons: string[] = [];
      reasons.push(`Edge +${edge.toFixed(1)}%`);
      reasons.push(`EV ${ev >= 0 ? "+" : ""}${ev.toFixed(1)}%`);
      if (edge >= HIGH_EDGE_THRESHOLD) reasons.push("⚠ HIGH EDGE — needs validation");
      if (s.modelProb > 60) reasons.push(`Model ${s.modelProb.toFixed(1)}%`);
      if (s.ml <= -150) reasons.push(`${formatOdds(s.ml)} favorite`);
      if (s.ml > 0) reasons.push(`${formatOdds(s.ml)} underdog`);
      if (lineMoveBonus >= 2) reasons.push("Sharp money");
      if (!pitcherConfirmed) reasons.push("⚠ TBD pitcher(s)");

      picks.push({
        team: s.team,
        opponent: s.opponent,
        ml: s.ml,
        impliedProb: Math.round(marketProbability(s.ml) * 10) / 10,
        fairMarketProb: Math.round(s.fairMkt * 10) / 10,
        modelProb: Math.round(s.modelProb * 10) / 10,
        edge: Math.round(edge * 10) / 10,
        ev: Math.round(ev * 10) / 10,
        reasons,
        score,
      });
    }
  }

  // Sort by score (edge-weighted), not by odds magnitude.
  // Take top 5 by score, ensuring no duplicate teams.
  const seen = new Set<string>();
  return picks
    .sort((a, b) => b.score - a.score)
    .filter(p => {
      if (seen.has(p.team)) return false;
      seen.add(p.team);
      return true;
    })
    .slice(0, 5);
}

// ---------------------------------------------------------------------------
// K-Strikeout Props (unchanged — purely statistical, not model-based)
// ---------------------------------------------------------------------------

export function analyzeKProps(games: Game[]): KProp[] {
  const props: (KProp & { score: number })[] = [];

  for (const game of games) {
    for (const side of ["away", "home"] as const) {
      const pitcher = side === "away" ? game.awayPitcher : game.homePitcher;
      const team = side === "away" ? game.awayTeam : game.homeTeam;
      const opponent = side === "away" ? game.homeTeam : game.awayTeam;
      const k9 = side === "away" ? game.awayK9 : game.homeK9;
      const avgK = side === "away" ? game.awayAvgK : game.homeAvgK;
      const overRate = side === "away" ? game.awayOver6_5 : game.homeOver6_5;

      if (!pitcher) continue;

      let score = 0;
      const reasons: string[] = [];

      if (k9 && k9 > 9) { score += 3; reasons.push(`K/9: ${k9.toFixed(1)}`); }
      else if (k9 && k9 > 8) { score += 1; reasons.push(`K/9: ${k9.toFixed(1)}`); }

      if (HIGH_K_OFFENSES.has(opponent)) { score += 2; reasons.push(`vs ${opponent} (high K rate)`); }
      if (LOW_K_OFFENSES.has(opponent)) score -= 1;
      if (overRate && overRate >= 0.6) { score += 3; reasons.push(`Over 6.5: ${(overRate * 100).toFixed(0)}%`); }
      if (avgK && avgK >= 7) { score += 2; reasons.push(`Avg ${avgK.toFixed(1)} K/start`); }

      if (score > 0) {
        props.push({
          pitcher,
          team,
          opponent,
          k9,
          avgK,
          over6_5Rate: overRate,
          reasons,
          score,
        });
      }
    }
  }

  return props.sort((a, b) => b.score - a.score).slice(0, 5);
}

// ---------------------------------------------------------------------------
// Over/Under Totals (unchanged — purely statistical, not model-based)
// ---------------------------------------------------------------------------

export function analyzeTotals(games: Game[]): TotalPick[] {
  const picks: (TotalPick & { score: number })[] = [];

  for (const game of games) {
    if (!game.overUnder) continue;

    let overVotes = 0;
    let underVotes = 0;
    let overReasons: string[] = [];
    let underReasons: string[] = [];

    // 1) Starting pitching signal
    const eras = [game.awayEra, game.homeEra].filter((e): e is number => !!e);
    if (eras.length === 2) {
      const avgEra = (eras[0] + eras[1]) / 2;
      if (avgEra <= 3.0) {
        underVotes += 2; underReasons.push(`Starters avg ERA ${avgEra.toFixed(2)} (elite pitching)`);
      } else if (avgEra <= 3.5) {
        underVotes += 1; underReasons.push(`Starters avg ERA ${avgEra.toFixed(2)}`);
      } else if (avgEra >= 5.0) {
        overVotes += 2; overReasons.push(`Starters avg ERA ${avgEra.toFixed(2)} (weak pitching)`);
      } else if (avgEra >= 4.5) {
        overVotes += 1; overReasons.push(`Starters avg ERA ${avgEra.toFixed(2)}`);
      }
    }

    // 2) Team scoring trends (runs per game)
    const rpg = [game.awayRunsPerGame, game.homeRunsPerGame].filter((v): v is number => !!v);
    if (rpg.length === 2) {
      const avgRpg = (rpg[0] + rpg[1]) / 2;
      if (avgRpg >= 5.0) {
        overVotes += 2; overReasons.push(`Offenses avg ${avgRpg.toFixed(2)} R/G`);
      } else if (avgRpg >= 4.6) {
        overVotes += 1; overReasons.push(`Offenses avg ${avgRpg.toFixed(2)} R/G`);
      } else if (avgRpg <= 3.8) {
        underVotes += 2; underReasons.push(`Offenses avg ${avgRpg.toFixed(2)} R/G`);
      } else if (avgRpg <= 4.2) {
        underVotes += 1; underReasons.push(`Offenses avg ${avgRpg.toFixed(2)} R/G`);
      }
    }

    // 3) Bullpen signal
    const bullpens = [game.awayBullpenEra, game.homeBullpenEra].filter((v): v is number => !!v);
    if (bullpens.length === 2) {
      const avgBp = (bullpens[0] + bullpens[1]) / 2;
      if (avgBp <= 3.3) {
        underVotes += 2; underReasons.push(`Bullpens avg ERA ${avgBp.toFixed(2)} (elite relief)`);
      } else if (avgBp <= 3.6) {
        underVotes += 1; underReasons.push(`Bullpens avg ERA ${avgBp.toFixed(2)}`);
      } else if (avgBp >= 4.5) {
        overVotes += 2; overReasons.push(`Bullpens avg ERA ${avgBp.toFixed(2)} (weak relief)`);
      } else if (avgBp >= 4.2) {
        overVotes += 1; overReasons.push(`Bullpens avg ERA ${avgBp.toFixed(2)}`);
      }
    }

    // 4) Extreme total lines
    if (game.overUnder >= 11.0) {
      overVotes += 2;
      overReasons.push(`High total ${game.overUnder.toFixed(1)}`);
    } else if (game.overUnder <= 7.0) {
      underVotes += 2;
      underReasons.push(`Low total ${game.overUnder.toFixed(1)}`);
    }

    // Decide by votes; ties produce no pick
    if (overVotes === underVotes) continue;
    const pick: "Over" | "Under" = overVotes > underVotes ? "Over" : "Under";
    const reasons = pick === "Over" ? overReasons : underReasons;

    picks.push({
      away: game.awayTeam,
      home: game.homeTeam,
      overUnder: game.overUnder,
      pick,
      reasons,
      score: Math.max(overVotes, underVotes),
    });
  }

  return picks.sort((a, b) => b.score - a.score).slice(0, 5);
}

// ---------------------------------------------------------------------------
// Parlay builder (updated to use ModelEdge with new fields)
// ---------------------------------------------------------------------------

export function buildParlays(edges: ModelEdge[], topKProps: KProp[], topTotals: TotalPick[] = []): Parlay[] {
  const parlays: Parlay[] = [];

  // Moneyline legs come from the model-edge layer (strongest positive edges),
  // capped at one leg per game so a same-game pair can't create correlated
  // legs (both teams of one game are never in the same parlay).
  const mlEdges: ModelEdge[] = [];
  const seenGames = new Set<string>();
  for (const e of edges) {
    if (seenGames.has(e.gameId)) continue;
    seenGames.add(e.gameId);
    mlEdges.push(e);
    if (mlEdges.length >= 3) break;
  }
  const mlOdds = mlEdges.map(e => e.ml);
  const mlLabels = mlEdges.map(e => `${e.team} ML (${formatOdds(e.ml)})`);

  // Estimate K prop odds
  const estimateKOdds = (prop: KProp): number => {
    if (prop.over6_5Rate && prop.over6_5Rate >= 0.55) return -120;
    if (prop.k9 && prop.k9 >= 9) return -110;
    if (prop.k9 && prop.k9 >= 8) return +100;
    return +110;
  };

  const kOdds = topKProps.slice(0, 2).map(estimateKOdds);
  const kLabels = topKProps.slice(0, 2).map((p, i) => `${p.pitcher} Over 6.5 Ks (${formatOdds(kOdds[i])})`);

  // Parlay 1: Top 3 ML (from model edges)
  if (mlOdds.length >= 3) {
    const p = calculateParlayPayout(mlOdds.slice(0, 3));
    parlays.push({ name: "Top 3 Model Edge MLs", legs: mlLabels.slice(0, 3), ...p });
  }

  // Parlay 2: 2 ML + 1 K
  if (mlOdds.length >= 2 && kOdds.length >= 1) {
    const p = calculateParlayPayout([mlOdds[0], mlOdds[1], kOdds[0]]);
    parlays.push({ name: "Strikeout Special (2 ML + 1 K)", legs: [mlLabels[0], mlLabels[1], kLabels[0]], ...p });
  }

  // Parlay 3: 2 ML + 2 K
  if (mlOdds.length >= 2 && kOdds.length >= 2) {
    const p = calculateParlayPayout([mlOdds[0], mlOdds[1], kOdds[0], kOdds[1]]);
    parlays.push({ name: "K Prop Stack (2 ML + 2 K)", legs: [mlLabels[0], mlLabels[1], kLabels[0], kLabels[1]], ...p });
  }

  // Parlay 4: 3 ML + 2 K
  if (mlOdds.length >= 3 && kOdds.length >= 2) {
    const p = calculateParlayPayout([...mlOdds.slice(0, 3), ...kOdds]);
    parlays.push({ name: "Grand Slam (3 ML + 2 K)", legs: [...mlLabels.slice(0, 3), ...kLabels], ...p });
  }

  // Parlay 5: 2 ML + Best Total (pick a total from a different game to
  // avoid correlated legs, e.g. a team ML + that same game's total)
  if (mlOdds.length >= 2 && topTotals.length >= 1) {
    const mlTeams = new Set<string>();
    for (const e of mlEdges.slice(0, 2)) {
      mlTeams.add(e.team);
      mlTeams.add(e.opponent);
    }
    const tp =
      topTotals.find(t => !mlTeams.has(t.away) && !mlTeams.has(t.home)) ??
      topTotals[0];
    const p = calculateParlayPayout([mlOdds[0], mlOdds[1], -110]);
    parlays.push({
      name: "Totals Special (2 ML + 1 O/U)",
      legs: [
        mlLabels[0],
        mlLabels[1],
        `${tp.away} @ ${tp.home} ${tp.pick} ${tp.overUnder.toFixed(1)} (-110)`,
      ],
      ...p,
    });
  }

  return parlays;
}
